### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by vipink1203** [teamclairvoyant/airflow-user-management-plugin#2]
Hi,

I tried using this plugin and I noticed even when the users are logged out they can access the user management page which shouldn't be an expected behavior when it comes to managing users and in security perspective.

I hope you find this useful for improving this plugin. 

Thanks for this plugin!

**Comment by balaramachandran** [comment]
@vipink1203 

I have added some workaround for security in my fork https://github.com/balaramachandran/airflow-user-management-plugin.

Please review and see if it is useful for your use case.

Thanks @rssanders3 for the plugin.

**Comment by sudhakar-nallam** [comment]
@vipink1203 this issues was taken care in #5
